# dtb-$(CONFIG_ARCH_MSM8996) += msm8996-v2-pmi8994-cdp.dtb \
#	msm8996-1.dtb \
	msm8996-2.dtb \
	msm8996-3.dtb \
	msm8996-4.dtb \
	msm8996-5.dtb \
	msm8996-6.dtb \
	msm8996-7.dtb \
	msm8996-8.dtb \
	msm8996-9.dtb \
	msm8996-10.dtb \
	msm8996-11.dtb \
	msm8996-12.dtb \
	msm8996-13.dtb \
	msm8996-14.dtb \
	msm8996-15.dtb \
	msm8996-16.dtb \
	msm8996-17.dtb \
	msm8996-18.dtb \
	msm8996-19.dtb \
	msm8996-20.dtb \
	msm8996-21.dtb \
	msm8996-22.dtb \
	msm8996-23.dtb \
	msm8996-24.dtb \
	msm8996-25.dtb \
	msm8996-26.dtb \
	msm8996-27.dtb \
	msm8996-28.dtb \
	msm8996-29.dtb \
	msm8996-30.dtb \
	msm8996-31.dtb \
	msm8996-32.dtb \
	msm8996-33.dtb \
	msm8996-34.dtb \
	msm8996-35.dtb \
	msm8996-36.dtb \
	msm8996-37.dtb \
	msm8996-38.dtb \
	msm8996-39.dtb \
	msm8996-40.dtb \
	msm8996-41.dtb \
	msm8996-42.dtb \
	msm8996-43.dtb \
	msm8996-44.dtb \
	msm8996-45.dtb \
	msm8996-46.dtb \
	msm8996-47.dtb \
	msm8996-48.dtb \
	msm8996-49.dtb \
	msm8996-50.dtb \
	msm8996-51.dtb \
	msm8996-52.dtb \
	msm8996-53.dtb \
	msm8996-54.dtb \
	msm8996-55.dtb \
	msm8996-56.dtb \
	msm8996-57.dtb \
	msm8996-58.dtb \
	msm8996-59.dtb \
	msm8996-60.dtb \
	msm8996-61.dtb \
	msm8996-62.dtb \
	msm8996-63.dtb \
	msm8996-64.dtb \
	msm8996-65.dtb \
	msm8996-66.dtb \
	msm8996-67.dtb \
	msm8996-68.dtb \
	msm8996-69.dtb \
	msm8996-70.dtb \
	msm8996-71.dtb \
	msm8996-72.dtb \
	msm8996-73.dtb \
	msm8996-74.dtb \
	msm8996-75.dtb \
	msm8996-76.dtb \
	msm8996-77.dtb \
	msm8996-78.dtb \
	msm8996-79.dtb \
	msm8996-80.dtb \
	msm8996-81.dtb \
	msm8996-82.dtb \
	msm8996-83.dtb \
	msm8996-84.dtb \
	msm8996-85.dtb \
	msm8996-86.dtb \
	msm8996-87.dtb \
	msm8996-88.dtb \
	msm8996-89.dtb \
	msm8996-90.dtb \

dtb-$(CONFIG_ARCH_MDM9640) += mdm9640-sim.dtb \
	mdm9640-rumi.dtb \
	mdm9640-emmc-cdp.dtb \
	mdm9640-nand-cdp.dtb \
	mdm9640-mtp.dtb

dtb-$(CONFIG_ARCH_MDMCALIFORNIUM) += mdmcalifornium-sim.dtb \
	mdmcalifornium-rumi.dtb \
	mdmcalifornium-emmc-cdp.dtb \
	mdmcalifornium-nand-cdp.dtb \
	mdmcalifornium-emmc-mtp.dtb \
	mdmcalifornium-nand-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8937) += msm8937-rumi.dtb \
	msm8937-pmi8950-cdp.dtb \
	msm8937-pmi8937-cdp.dtb \
	msm8937-pmi8950-ext-codec-cdp.dtb \
	msm8937-pmi8950-mtp.dtb \
	msm8937-pmi8937-mtp.dtb \
	msm8937-pmi8950-rcm.dtb \
	msm8937-pmi8937-rcm.dtb \
	msm8937-pmi8950-qrd-sku1.dtb \
	msm8937-pmi8937-qrd-sku2.dtb \
	msm8937-pmi8950-qrd-sku1-dvt1.dtb \
	msm8937-pmi8937-qrd-sku2-dvt1.dtb \
	apq8037-pmi8950-cdp.dtb \
	apq8037-pmi8937-cdp.dtb \
	apq8037-pmi8950-mtp.dtb \
	apq8037-pmi8937-mtp.dtb

dtb-$(CONFIG_ARCH_MSMGOLD) += msmgold-rumi.dtb \
	apqgold-pmi8937-cdp.dtb \
	apqgold-pmi8937-mtp.dtb \
	apqgold-pmi8950-cdp.dtb \
	apqgold-pmi8950-mtp.dtb \
	msmgold-pmi8937-cdp.dtb \
	msmgold-pmi8937-mtp.dtb \
	msmgold-pmi8950-cdp.dtb \
	msmgold-pmi8950-ext-codec-cdp.dtb \
	msmgold-pmi8950-mtp.dtb \
	msmgold-pmi8937-rcm.dtb \
	msmgold-pmi8950-rcm.dtb

dtb-$(CONFIG_ARCH_MSMTITANIUM) += msmtitanium-sim.dtb \
	msmtitanium-rumi.dtb \
	msmtitanium-cdp.dtb \
	msmtitanium-mtp.dtb \
	msmtitanium-ext-codec-mtp.dtb \
	msmtitanium-qrd-sku3.dtb \
	msmtitanium-rcm.dtb \
	msmtitanium-ext-codec-rcm.dtb \
	apqtitanium-cdp.dtb \
	apqtitanium-mtp.dtb

dtb-$(CONFIG_ARCH_MDM9607) += mdm9607-rumi.dtb \
	mdm9607-cdp.dtb \
	mdm9607-mtp.dtb \
	mdm9607-rcm.dtb \
	mdm9607-mtp-sdcard.dtb

dtb-$(CONFIG_ARCH_MSM8916) += msm8952-qrd-skum.dtb \
       msm8952-cdp.dtb \
       msm8952-ext-codec-cdp.dtb \
       msm8952-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8909) += msm8909-pm8916-mtp.dtb \
	msm8909w-wtp.dtb \
	apq8009w-wtp.dtb

ifeq ($(CONFIG_ARM64),y)
always          := $(dtb-y)
subdir-y        := $(dts-dirs)
else
targets += dtbs
targets += $(addprefix ../, $(dtb-y))

$(obj)/../%.dtb: $(src)/%.dts FORCE
        $(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
